# Generated by Django 5.2 on 2025-04-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Lunch (13:00)', 'Lunch 13:00'), ('Dinner (19:00)', 'Dinner 19:00')], max_length=14)),
                ('username', models.CharField(max_length=150)),
                ('booking_title', models.CharField(max_length=50)),
                ('number_of_seats', models.SmallIntegerField()),
                ('date', models.DateField()),
                ('contact_number', models.CharField(max_length=12)),
            ],
        ),
    ]
